### ISSUE TITLE
Only PS4 works now

### ISSUE THREAD

**Issue by xetsubou** [Tustin/PlayStationDiscord#106]
**Information**
- OS: Windows10
- Version: Latest

**Describe the bug**
So the PS4 works fine, but PS3 no longer works, says I'm online but after a few seconds it says error communicating with discord. Any fix?

**Log**
[2020-07-18 03:32:58.328] [info] PlayStationDiscord-Games has not been updated, using cached version
[2020-07-18 03:32:58.404] [info] Running refreshAuthTokensLoop
[2020-07-18 03:32:58.427] [info] Logged in with existing refresh token
[2020-07-18 03:32:58.787] [info] Starting rich presence loop
[2020-07-18 03:34:15.793] [info] PlayStationDiscord-Games has not been updated, using cached version
[2020-07-18 03:34:15.929] [info] Running refreshAuthTokensLoop
[2020-07-18 03:34:15.951] [info] Logged in with existing refresh token
[2020-07-18 03:34:16.284] [info] Starting rich presence loop
[2020-07-18 03:35:16.528] [info] Switching console to  PS3
[2020-07-18 03:35:16.556] [info] DiscordController init
[2020-07-18 03:35:16.562] [info] Switched console to PlayStation 3
[2020-07-18 03:35:16.568] [info] Status set to online
[2020-07-18 03:35:16.575] [info] Updated rich presence
[2020-07-18 03:35:17.314] [error] An error occurred while communicating with Discord Error
    at RPCClient._onRpcMessage (D:\Documents\psdiscord downgrade\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\client.js:177:19)
    at IPCTransport.emit (events.js:203:13)
    at D:\Documents\psdiscord downgrade\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:134:18
    at decode (D:\Documents\psdiscord downgrade\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.<anonymous> (D:\Documents\psdiscord downgrade\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (events.js:203:13)
    at emitReadable_ (_stream_readable.js:565:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[2020-07-18 03:35:17.324] [warn] DiscordController disconnected
[2020-07-18 03:35:17.330] [info] Stopped rich presence loop
[2020-07-18 03:35:21.404] [info] Starting rich presence loop
[2020-07-18 03:35:21.612] [info] Switching console to  PS3
[2020-07-18 03:35:21.619] [info] DiscordController init
[2020-07-18 03:35:21.625] [info] Switched console to PlayStation 3
[2020-07-18 03:35:21.630] [info] Status set to online
[2020-07-18 03:35:36.902] [info] Switching console to  PS3
[2020-07-18 03:35:36.908] [info] DiscordController init
[2020-07-18 03:35:36.916] [info] Switched console to PlayStation 3
[2020-07-18 03:35:36.921] [info] Status set to online
[2020-07-18 03:35:36.928] [info] Updated rich presence
[2020-07-18 03:35:46.908] [error] An error occurred while communicating with Discord Error: RPC_CONNECTION_TIMEOUT
    at Timeout._onTimeout (D:\Documents\psdiscord downgrade\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\client.js:99:47)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2020-07-18 03:35:46.915] [warn] DiscordController disconnected
[2020-07-18 03:35:46.921] [info] Stopped rich presence loop
[2020-07-18 03:40:06.236] [info] PlayStationDiscord-Games has not been updated, using cached version
[2020-07-18 03:40:06.481] [info] Running refreshAuthTokensLoop
[2020-07-18 03:40:06.498] [info] Logged in with existing refresh token
[2020-07-18 03:40:07.185] [info] Starting rich presence loop
[2020-07-18 03:40:07.524] [info] Switching console to  PS3
[2020-07-18 03:40:07.546] [info] DiscordController init
[2020-07-18 03:40:07.552] [info] Switched console to PlayStation 3
[2020-07-18 03:40:07.558] [info] Status set to online
[2020-07-18 03:40:07.564] [info] Updated rich presence
[2020-07-18 03:41:38.602] [info] Stopped rich presence loop
[2020-07-18 03:41:38.628] [error] An error occurred while communicating with Discord Error: connection closed
    at _expecting.forEach (C:\psdiscord\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\client.js:107:20)
    at Map.forEach (<anonymous>)
    at IPCTransport.transport.once (C:\psdiscord\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\client.js:106:25)
    at Object.onceWrapper (events.js:273:13)
    at IPCTransport.emit (events.js:182:13)
    at decode (C:\psdiscord\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:137:18)
    at decode (C:\psdiscord\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.socket.on (C:\psdiscord\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:534:12)
[2020-07-18 03:41:40.065] [warn] DiscordController disconnected
[2020-07-18 03:41:40.072] [info] Stopped rich presence loop
[2020-07-18 03:41:41.246] [info] Starting rich presence loop
[2020-07-18 03:41:41.496] [info] Switching console to  PS3
[2020-07-18 03:41:41.502] [info] DiscordController init
[2020-07-18 03:41:41.508] [info] Switched console to PlayStation 3
[2020-07-18 03:41:41.514] [info] Status set to online
[2020-07-18 03:41:41.519] [info] Updated rich presence

**Comment by ghaztt** [comment]
psvita is not working too

**Comment by xetsubou** [comment]
still checking this regularly, will it ever get fixed? wish i knew how to fix it myself

**Comment by WaseWalayse** [comment]
Hoping for a fix as well for some time already..

**Comment by papin97** [comment]
I got the same issue, but the error is `undefined` instead of something like above
```
[2020-09-03 15:50:30.529] [info] PlayStationDiscord-Games has not been updated, using cached version
[2020-09-03 15:50:30.949] [info] Running refreshAuthTokensLoop
[2020-09-03 15:50:30.962] [info] Logged in with existing refresh token
[2020-09-03 15:50:31.399] [info] Starting rich presence loop
[2020-09-03 15:50:32.005] [info] Switching console to  PS3
[2020-09-03 15:50:32.023] [info] DiscordController init
[2020-09-03 15:50:32.024] [info] Switched console to PlayStation 3
[2020-09-03 15:50:32.024] [info] Game has switched PAYDAY 2
[2020-09-03 15:50:32.026] [warn] Game icon not found in supported games store PAYDAY 2 NPUB31294_00
[2020-09-03 15:50:32.027] [info] Updated rich presence
[2020-09-03 15:50:33.267] [error] An error occurred while communicating with Discord undefined
[2020-09-03 15:50:36.269] [warn] DiscordController disconnected
[2020-09-03 15:50:36.270] [info] Stopped rich presence loop
```

**Comment by Alexis1887** [comment]
Same here
