### ISSUE TITLE
Not showing up online

### ISSUE THREAD

**Issue by RazzeeX** [Tustin/PlayStationDiscord#131]
**Information**
- OS: Windows 7 Ultimate x64
- Version: Latest

**Describe the bug**
Hello.

So my issue is: when I use the 3.1.2 version, it initially recognizes that I'm playing a PS3 game; in this case, Gran Turismo 6, but the app returns an error.

![image](https://user-images.githubusercontent.com/69221199/102712106-31ef5800-429d-11eb-99b5-af3a0228be97.png)

Once I update the app to 3.2.0, it displays that I am offline.

![image](https://user-images.githubusercontent.com/69221199/102712164-a7f3bf00-429d-11eb-9414-3f563e39bf0d.png)

Also, the "Disable" and "Sign out" options don't do anything once updated to 3.2.0.

![image](https://user-images.githubusercontent.com/69221199/102712282-b098c500-429e-11eb-85e4-2d0a6ce70450.png)

**Log**
Provide the bottom (or all) of your log file for PlayStationDiscord.
- Windows: `%APPDATA%\PlayStationDiscord\log.log`
- macOS: `~/Library/Logs/PlayStationDiscord/log.log`
- Linux: `~/.config/PlayStationDiscord/log.log`
```
[2020-12-20 08:51:52.144] [info] Saved new version of games.json
[2020-12-20 08:53:43.868] [info] Running refreshAuthTokensLoop
[2020-12-20 08:53:43.876] [info] Saved oauth tokens
[2020-12-20 08:53:44.482] [info] Starting rich presence loop
[2020-12-20 08:53:44.987] [info] Switching console to  PS3
[2020-12-20 08:53:45.007] [info] DiscordController init
[2020-12-20 08:53:45.008] [info] Switched console to PlayStation 3
[2020-12-20 08:53:45.009] [info] Status set to online
[2020-12-20 08:53:45.010] [info] Updated rich presence
[2020-12-20 08:53:45.224] [error] An error occurred while communicating with Discord undefined
[2020-12-20 08:53:48.417] [warn] DiscordController disconnected
[2020-12-20 08:53:48.419] [info] Stopped rich presence loop
[2020-12-20 09:02:55.682] [info] PlayStationDiscord-Games has not been updated, using cached version
[2020-12-20 09:02:56.155] [error] Failed logging in with saved refresh token { error: 'invalid_scope',
  error_description: 'Invalid scope',
  docs: 'https://auth.api.sonyentertainmentnetwork.com/docs/',
  error_code: 4153 }
[2020-12-20 09:03:42.586] [info] Running refreshAuthTokensLoop
[2020-12-20 09:03:42.596] [info] Saved oauth tokens
[2020-12-20 09:03:42.849] [info] Starting rich presence loop
[2020-12-20 09:03:43.244] [info] Switching console to  PS3
[2020-12-20 09:03:43.264] [info] DiscordController init
[2020-12-20 09:03:43.264] [info] Switched console to PlayStation 3
[2020-12-20 09:03:43.265] [info] Game has switched Gran Turismo®6
[2020-12-20 09:03:43.266] [warn] Game icon not found in supported games store Gran Turismo®6 BCUS99247_00
[2020-12-20 09:03:43.480] [error] An error occurred while communicating with Discord undefined
[2020-12-20 09:03:46.923] [warn] DiscordController disconnected
[2020-12-20 09:03:46.928] [info] Stopped rich presence loop
[2020-12-20 09:07:04.125] [info] PlayStationDiscord-Games has not been updated, using cached version
[2020-12-20 09:07:04.316] [error] Failed logging in with saved refresh token { error: 'invalid_scope',
  error_description: 'Invalid scope',
  docs: 'https://auth.api.sonyentertainmentnetwork.com/docs/',
  error_code: 4153 }
[2020-12-20 09:07:54.672] [info] Running refreshAuthTokensLoop
[2020-12-20 09:07:54.683] [info] Saved oauth tokens
[2020-12-20 09:07:54.949] [info] Starting rich presence loop
[2020-12-20 09:07:55.362] [info] Switching console to  PS3
[2020-12-20 09:07:55.383] [info] DiscordController init
[2020-12-20 09:07:55.383] [info] Switched console to PlayStation 3
[2020-12-20 09:07:55.384] [info] Game has switched Gran Turismo®6
[2020-12-20 09:07:55.385] [warn] Game icon not found in supported games store Gran Turismo®6 BCUS99247_00
[2020-12-20 09:07:55.596] [error] An error occurred while communicating with Discord undefined
[2020-12-20 09:09:58.733] [warn] DiscordController disconnected
[2020-12-20 09:09:58.734] [info] Stopped rich presence loop
[2020-12-20 09:12:08.910] [info] PlayStationDiscord-Games has not been updated, using cached version
[2020-12-20 09:12:09.168] [error] Failed logging in with saved refresh token { error: 'invalid_scope',
  error_description: 'Invalid scope',
  docs: 'https://auth.api.sonyentertainmentnetwork.com/docs/',
  error_code: 4153 }
[2020-12-20 09:13:03.764] [info] Running refreshAuthTokensLoop
[2020-12-20 09:13:03.776] [info] Saved oauth tokens
[2020-12-20 09:13:04.077] [info] Starting rich presence loop
[2020-12-20 09:13:04.488] [info] Switching console to  PS3
[2020-12-20 09:13:04.508] [info] DiscordController init
[2020-12-20 09:13:04.508] [info] Switched console to PlayStation 3
[2020-12-20 09:13:04.509] [info] Game has switched Gran Turismo®6
[2020-12-20 09:13:04.510] [warn] Game icon not found in supported games store Gran Turismo®6 BCUS99247_00
[2020-12-20 09:13:04.511] [info] Updated rich presence
[2020-12-20 09:13:04.724] [error] An error occurred while communicating with Discord undefined
[2020-12-20 09:13:57.047] [warn] DiscordController disconnected
[2020-12-20 09:13:57.049] [info] Stopped rich presence loop
[2020-12-20 09:24:29.537] [info] PlayStationDiscord-Games has not been updated, using cached version
[2020-12-20 09:24:29.826] [error] Failed logging in with saved refresh token { error: 'invalid_scope',
  error_description: 'Invalid scope',
  docs: 'https://auth.api.sonyentertainmentnetwork.com/docs/',
  error_code: 4153 }
[2020-12-20 09:24:39.536] [info] PlayStationDiscord-Games has not been updated, using cached version
[2020-12-20 09:24:39.787] [error] Failed logging in with saved refresh token { error: 'invalid_scope',
  error_description: 'Invalid scope',
  docs: 'https://auth.api.sonyentertainmentnetwork.com/docs/',
  error_code: 4153 }
[2020-12-20 09:26:00.321] [info] Running refreshAuthTokensLoop
[2020-12-20 09:26:00.330] [info] Saved oauth tokens
[2020-12-20 09:26:00.579] [info] Starting rich presence loop
[2020-12-20 09:26:00.967] [info] Switching console to  PS3
[2020-12-20 09:26:00.987] [info] DiscordController init
[2020-12-20 09:26:00.987] [info] Switched console to PlayStation 3
[2020-12-20 09:26:00.988] [info] Game has switched Gran Turismo®6
[2020-12-20 09:26:00.989] [warn] Game icon not found in supported games store Gran Turismo®6 BCUS99247_00
[2020-12-20 09:26:00.990] [info] Updated rich presence
[2020-12-20 09:26:01.199] [error] An error occurred while communicating with Discord undefined
[2020-12-20 09:28:40.165] [warn] DiscordController disconnected
[2020-12-20 09:28:40.166] [info] Stopped rich presence loop
[2020-12-20 09:32:14.615] [info] PlayStationDiscord-Games has not been updated, using cached version
[2020-12-20 09:32:14.946] [error] Failed logging in with saved refresh token { error: 'invalid_scope',
  error_description: 'Invalid scope',
  docs: 'https://auth.api.sonyentertainmentnetwork.com/docs/',
  error_code: 4153 }
[2020-12-20 09:32:50.247] [info] Running refreshAuthTokensLoop
[2020-12-20 09:32:50.257] [info] Saved oauth tokens
[2020-12-20 09:32:50.512] [info] Starting rich presence loop
[2020-12-20 09:32:50.926] [info] Switching console to  PS3
[2020-12-20 09:32:50.945] [info] DiscordController init
[2020-12-20 09:32:50.946] [info] Switched console to PlayStation 3
[2020-12-20 09:32:50.947] [info] Game has switched Gran Turismo®6
[2020-12-20 09:32:50.948] [warn] Game icon not found in supported games store Gran Turismo®6 BCUS99247_00
[2020-12-20 09:32:50.949] [info] Updated rich presence
[2020-12-20 09:32:51.159] [error] An error occurred while communicating with Discord undefined
[2020-12-20 09:33:05.970] [warn] DiscordController disconnected
[2020-12-20 09:33:05.971] [info] Stopped rich presence loop
[2020-12-20 09:33:15.547] [info] Starting rich presence loop
[2020-12-20 09:33:15.851] [info] Switching console to  PS3
[2020-12-20 09:33:15.853] [info] DiscordController init
[2020-12-20 09:33:15.853] [info] Switched console to PlayStation 3
[2020-12-20 09:33:15.854] [info] Game has switched Gran Turismo®6
[2020-12-20 09:33:15.854] [warn] Game icon not found in supported games store Gran Turismo®6 BCUS99247_00
[2020-12-20 09:33:15.855] [info] Updated rich presence
[2020-12-20 09:33:16.054] [error] An error occurred while communicating with Discord undefined
[2020-12-20 09:33:17.659] [warn] DiscordController disconnected
[2020-12-20 09:33:17.660] [info] Stopped rich presence loop
[2020-12-20 09:33:18.554] [info] Starting rich presence loop
[2020-12-20 09:33:18.862] [info] Switching console to  PS3
[2020-12-20 09:33:18.863] [info] DiscordController init
[2020-12-20 09:33:18.863] [info] Switched console to PlayStation 3
[2020-12-20 09:33:18.864] [info] Game has switched Gran Turismo®6
[2020-12-20 09:33:18.865] [warn] Game icon not found in supported games store Gran Turismo®6 BCUS99247_00
[2020-12-20 09:33:21.179] [error] An error occurred while communicating with Discord undefined
[2020-12-20 09:33:23.676] [warn] DiscordController disconnected
[2020-12-20 09:33:23.677] [info] Stopped rich presence loop
[2020-12-20 09:33:23.683] [info] Starting rich presence loop
[2020-12-20 09:33:23.970] [info] Switching console to  PS3
[2020-12-20 09:33:23.971] [info] DiscordController init
[2020-12-20 09:33:23.972] [info] Switched console to PlayStation 3
[2020-12-20 09:33:23.972] [info] Game has switched Gran Turismo®6
[2020-12-20 09:33:23.973] [warn] Game icon not found in supported games store Gran Turismo®6 BCUS99247_00
[2020-12-20 09:33:23.974] [info] Updated rich presence
[2020-12-20 09:33:24.488] [info] Stopped rich presence loop
[2020-12-20 09:33:24.490] [error] An error occurred while communicating with Discord undefined
[2020-12-20 09:33:25.258] [warn] DiscordController disconnected
[2020-12-20 09:33:25.259] [info] Stopped rich presence loop
[2020-12-20 09:34:50.822] [info] Starting rich presence loop
[2020-12-20 09:34:51.117] [info] Switching console to  PS3
[2020-12-20 09:34:51.118] [info] DiscordController init
[2020-12-20 09:34:51.118] [info] Switched console to PlayStation 3
[2020-12-20 09:34:51.119] [info] Game has switched Gran Turismo®6
[2020-12-20 09:34:51.120] [warn] Game icon not found in supported games store Gran Turismo®6 BCUS99247_00
[2020-12-20 09:34:51.120] [info] Updated rich presence
[2020-12-20 09:34:51.301] [error] An error occurred while communicating with Discord undefined
[2020-12-20 09:34:52.353] [warn] DiscordController disconnected
[2020-12-20 09:34:52.354] [info] Stopped rich presence loop
[2020-12-20 09:34:53.979] [info] Starting rich presence loop
[2020-12-20 09:34:54.248] [info] Switching console to  PS3
[2020-12-20 09:34:54.248] [info] DiscordController init
[2020-12-20 09:34:54.249] [info] Switched console to PlayStation 3
[2020-12-20 09:34:54.249] [info] Game has switched Gran Turismo®6
[2020-12-20 09:34:54.250] [warn] Game icon not found in supported games store Gran Turismo®6 BCUS99247_00
[2020-12-20 09:34:54.430] [error] An error occurred while communicating with Discord undefined
[2020-12-20 09:34:55.515] [warn] DiscordController disconnected
[2020-12-20 09:34:55.516] [info] Stopped rich presence loop
[2020-12-20 09:34:56.221] [info] Starting rich presence loop
[2020-12-20 09:34:56.496] [info] Switching console to  PS3
[2020-12-20 09:34:56.497] [info] DiscordController init
[2020-12-20 09:34:56.498] [info] Switched console to PlayStation 3
[2020-12-20 09:34:56.498] [info] Game has switched Gran Turismo®6
[2020-12-20 09:34:56.499] [warn] Game icon not found in supported games store Gran Turismo®6 BCUS99247_00
[2020-12-20 09:34:56.500] [info] Updated rich presence
[2020-12-20 09:35:06.498] [error] An error occurred while communicating with Discord Error: RPC_CONNECTION_TIMEOUT
    at Timeout.setTimeout (C:\Program Files\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\client.js:99:47)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at unrefdHandle (timers.js:509:7)
    at Timer.processTimers (timers.js:211:12)
[2020-12-20 09:35:29.135] [warn] DiscordController disconnected
[2020-12-20 09:35:29.137] [info] Stopped rich presence loop
[2020-12-20 09:35:29.977] [info] Starting rich presence loop
[2020-12-20 09:35:30.267] [info] Switching console to  PS3
[2020-12-20 09:35:30.268] [info] DiscordController init
[2020-12-20 09:35:30.269] [info] Switched console to PlayStation 3
[2020-12-20 09:35:30.269] [info] Game has switched Gran Turismo®6
[2020-12-20 09:35:30.270] [warn] Game icon not found in supported games store Gran Turismo®6 BCUS99247_00
[2020-12-20 09:35:39.231] [info] Stopped rich presence loop
[2020-12-20 09:35:39.232] [error] An error occurred while communicating with Discord undefined
[2020-12-20 09:35:40.475] [warn] DiscordController disconnected
[2020-12-20 09:35:40.476] [info] Stopped rich presence loop
[2020-12-20 09:36:30.910] [info] Running refreshAuthTokensLoop
[2020-12-20 09:36:30.917] [info] Saved oauth tokens
[2020-12-20 09:36:31.211] [info] Starting rich presence loop
[2020-12-20 09:36:31.555] [info] Switching console to  PS3
[2020-12-20 09:36:31.556] [info] DiscordController init
[2020-12-20 09:36:31.557] [info] Switched console to PlayStation 3
[2020-12-20 09:36:31.558] [info] Game has switched Gran Turismo®6
[2020-12-20 09:36:31.558] [warn] Game icon not found in supported games store Gran Turismo®6 BCUS99247_00
[2020-12-20 09:36:31.559] [info] Updated rich presence
[2020-12-20 09:36:31.748] [error] An error occurred while communicating with Discord undefined
[2020-12-20 09:36:34.050] [warn] DiscordController disconnected
[2020-12-20 09:36:34.051] [info] Stopped rich presence loop

```

**Additional context**

**Comment by asc3ns10n** [comment]
Same as #119

**Comment by michael-shobo** [comment]
The error happens when you don't have discord running before you start the PlayStationDiscord 

Try starting Discord first before starting up the app

And same, the sign out button doesn't work

**Comment by madridplayz** [comment]
for me it just says im offline everything else works pls help
