### ISSUE TITLE
RDR2 Icon does not appear

### ISSUE THREAD

**Issue by ProLiteAD** [Tustin/PlayStationDiscord#151]
**Information**
- OS: Windows 10
- Version: Latest

**Describe the bug**
When I play RDR2 online it doesn't show the image on discord. It might be because I am on PS5 or because I only have the online version?

**Log**
Provide the bottom (or all) of your log file for PlayStationDiscord.
- Windows: `AppData\Roaming\playstationdiscord\logs\mani.txt`
```
[2021-02-19 14:55:44.047] [info] Saved new version of games.json
[2021-02-19 14:58:24.704] [info] Running refreshAuthTokensLoop
[2021-02-19 14:58:24.841] [info] Saved oauth tokens
[2021-02-19 14:58:26.194] [info] Starting rich presence loop
[2021-02-19 14:58:26.715] [info] Switching console to  PS5
[2021-02-19 14:58:26.755] [info] DiscordController init
[2021-02-19 14:58:26.757] [info] Switched console to PlayStation 5
[2021-02-19 14:58:26.759] [info] Status set to online
[2021-02-19 14:58:26.762] [info] Updated rich presence
[2021-02-19 14:58:56.443] [info] Game has switched Red Dead Redemption 2
[2021-02-19 14:58:56.492] [warn] Game icon not found in supported games store Red Dead Redemption 2 CUSA08519_00
[2021-02-19 14:58:56.495] [info] Updated rich presence
[2021-02-19 14:59:11.439] [info] Game status has changed Idle
[2021-02-19 14:59:11.441] [info] Updated rich presence
[2021-02-19 15:00:26.502] [info] Game has switched Apex Legends
[2021-02-19 15:00:26.509] [warn] Game icon not found in supported games store Apex Legends CUSA12552_00
[2021-02-19 15:00:26.511] [info] Updated rich presence
[2021-02-19 15:00:42.494] [info] Status set to online
[2021-02-19 15:00:42.499] [info] Updated rich presence
[2021-02-19 15:01:11.536] [info] DiscordController stopped because the user is not online on PlayStation
[2021-02-19 15:01:26.480] [info] Switching console to  PS5
[2021-02-19 15:01:26.483] [info] DiscordController init
[2021-02-19 15:01:26.485] [info] Switched console to PlayStation 5
[2021-02-19 15:01:26.486] [info] Status set to online
[2021-02-19 15:01:26.488] [info] Updated rich presence
[2021-02-19 15:03:26.527] [info] Game has switched Red Dead Redemption 2
[2021-02-19 15:03:26.556] [warn] Game icon not found in supported games store Red Dead Redemption 2 CUSA08519_00
[2021-02-19 15:03:26.560] [info] Updated rich presence
[2021-02-19 15:03:41.554] [info] Game status has changed Idle
[2021-02-19 15:03:41.557] [info] Updated rich presence
[2021-02-19 15:06:11.546] [info] Game has switched Dead by Daylight
[2021-02-19 15:06:11.560] [info] Using game icon since it is supported
[2021-02-19 15:06:11.562] [info] Updated rich presence
[2021-02-19 15:08:56.700] [info] Status set to online
[2021-02-19 15:08:56.702] [info] Updated rich presence
[2021-02-19 15:12:11.588] [info] Game has switched Apex Legends
[2021-02-19 15:12:11.594] [warn] Game icon not found in supported games store Apex Legends CUSA12552_00
[2021-02-19 15:12:11.597] [info] Updated rich presence
[2021-02-19 15:12:26.581] [info] Game status has changed Main Menu
[2021-02-19 15:12:26.586] [info] Updated rich presence
[2021-02-19 15:12:56.684] [info] Game status has changed Lobby
[2021-02-19 15:12:56.689] [info] Updated rich presence
[2021-02-19 15:43:43.563] [info] PlayStationDiscord-Games has not been updated, using cached version
[2021-02-19 15:43:43.684] [info] Running refreshAuthTokensLoop
[2021-02-19 15:43:43.736] [info] Logged in with existing refresh token
[2021-02-19 15:43:46.297] [info] Starting rich presence loop
[2021-02-19 15:43:46.825] [info] Switching console to  PS5
[2021-02-19 15:43:46.863] [info] DiscordController init
[2021-02-19 15:43:46.865] [info] Switched console to PlayStation 5
[2021-02-19 15:43:46.868] [info] Status set to online
[2021-02-19 15:43:46.871] [info] Updated rich presence
[2021-02-19 15:45:15.740] [warn] Tray notification not shown because notifications aren't supported on this platform win32
[2021-02-19 15:51:01.607] [info] Game has switched Red Dead Redemption 2
[2021-02-19 15:51:01.617] [warn] Game icon not found in supported games store Red Dead Redemption 2 CUSA08519_00
[2021-02-19 15:51:01.619] [info] Updated rich presence
[2021-02-19 15:52:31.623] [info] Game status has changed Playing Red Dead Online: Moseying in Scarlett Meadows
[2021-02-19 15:52:31.629] [info] Updated rich presence
[2021-02-19 15:53:01.644] [info] Game status has changed Playing Red Dead Online: Moseying in Rhodes
[2021-02-19 15:53:01.646] [info] Updated rich presence
[2021-02-19 15:53:31.710] [info] Game status has changed Playing Red Dead Online: Moseying in Saint Denis
[2021-02-19 15:53:31.714] [info] Updated rich presence
[2021-02-19 15:55:08.884] [error] An error occurred while communicating with Discord Error: connection closed
    at C:\Program Files\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\client.js:115:20
    at Map.forEach (<anonymous>)
    at IPCTransport.<anonymous> (C:\Program Files\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\client.js:114:25)
    at Object.onceWrapper (events.js:417:26)
    at IPCTransport.emit (events.js:310:20)
    at IPCTransport.onClose (C:\Program Files\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:151:10)
    at Socket.emit (events.js:310:20)
    at Pipe.<anonymous> (net.js:672:12)
[2021-02-19 15:55:08.946] [warn] DiscordController disconnected
[2021-02-19 15:55:08.949] [info] Stopped rich presence loop
[2021-02-19 15:56:23.797] [info] PlayStationDiscord-Games has not been updated, using cached version
[2021-02-19 15:56:24.061] [info] Running refreshAuthTokensLoop
[2021-02-19 15:56:24.139] [info] Logged in with existing refresh token
[2021-02-19 15:56:24.853] [info] Starting rich presence loop
[2021-02-19 15:56:25.059] [warn] Tray notification not shown because notifications aren't supported on this platform win32
[2021-02-19 15:56:26.321] [info] Switching console to  PS5
[2021-02-19 15:56:26.373] [info] DiscordController init
[2021-02-19 15:56:26.375] [info] Switched console to PlayStation 5
[2021-02-19 15:56:26.377] [info] Game has switched Red Dead Redemption 2
[2021-02-19 15:56:26.395] [warn] Game icon not found in supported games store Red Dead Redemption 2 CUSA08519_00
[2021-02-19 15:56:26.398] [info] Updated rich presence
[2021-02-19 16:27:10.604] [info] Game has switched Bloodborne™
[2021-02-19 16:27:10.637] [warn] Game icon not found in supported games store Bloodborne™ CUSA03173_00
[2021-02-19 16:27:10.643] [info] Updated rich presence
[2021-02-19 16:27:25.210] [info] Game has switched Dead by Daylight
[2021-02-19 16:27:25.223] [info] Using game icon since it is supported
[2021-02-19 16:27:25.228] [info] Updated rich presence
[2021-02-19 16:27:40.232] [info] Game has switched Dishonored 2
[2021-02-19 16:27:40.259] [warn] Game icon not found in supported games store Dishonored 2 CUSA03603_00
[2021-02-19 16:27:40.269] [info] Updated rich presence
[2021-02-19 16:27:55.197] [info] Status set to online
[2021-02-19 16:27:55.201] [info] Updated rich presence
[2021-02-19 16:29:25.201] [info] Game has switched ASTRO's PLAYROOM
[2021-02-19 16:29:25.208] [info] Using game icon since it is supported
[2021-02-19 16:29:25.212] [info] Updated rich presence
[2021-02-19 16:30:10.193] [info] Status set to online
[2021-02-19 16:30:10.197] [info] Updated rich presence
[2021-02-19 17:28:26.172] [info] PlayStationDiscord-Games has not been updated, using cached version
[2021-02-19 17:28:26.410] [info] Running refreshAuthTokensLoop
[2021-02-19 17:28:26.465] [info] Logged in with existing refresh token
[2021-02-19 17:28:27.260] [info] Starting rich presence loop
[2021-02-19 17:28:27.802] [info] Switching console to  PS5
[2021-02-19 17:28:27.849] [info] DiscordController init
[2021-02-19 17:28:27.853] [info] Switched console to PlayStation 5
[2021-02-19 17:28:27.858] [info] Status set to online
[2021-02-19 17:28:27.862] [info] Updated rich presence
[2021-02-19 17:29:12.580] [info] Game has switched Red Dead Redemption 2
[2021-02-19 17:29:12.596] [warn] Game icon not found in supported games store Red Dead Redemption 2 CUSA08519_00
[2021-02-19 17:29:12.599] [info] Updated rich presence
[2021-02-19 17:29:27.515] [info] Game status has changed Idle
[2021-02-19 17:29:27.517] [info] Updated rich presence
[2021-02-19 17:30:44.574] [info] Stopped rich presence loop
```

**Additional context**
![image](https://user-images.githubusercontent.com/77837782/108539538-0bb75a00-72d8-11eb-948e-4ef9173b27f6.png)
I've checked the supported games and it said that RDR2 was supported as well.

**Comment by Tustin** [comment]
Yes, PS5 is the reason why. Basically, for Discord to show the right console name, I need to have two separate applications for PS4/PS5. The main problem here is that for each application, Discord only allows 150 assets (game images), which makes it difficult to include PS4 game images on the PS5 application. I know it sucks but unfortunately I cannot do anything unless Discord increases the asset limit or some how lets you share assets across applications ☹️

**Comment by ProLiteAD** [comment]
I see that makes sense.

This might be asking a bit too much but I think the way Xbox displays their info for discord is a bit cleaner, where they don’t even display the console name, just a small logo and the name of the game, do you think this would fix it?

**Comment by ProLiteAD** [comment]
Wow I understand I did a bit of research wondering if it was possible for the asset limit to increase but apparently Discord just doesn’t respond :/

**Comment by Tustin** [comment]
@ProLiteAD You'd have to fork the repo and change the client id for whichever console you are using with your own Discord application that has the assets you want. In the future I may add a setting which lets you change the client id so you can use whatever game images you want
