### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by Haru-Yuki** [Tustin/PlayStationDiscord#17]
Version 1.2.1 works fine, but when using 2.1.0.0 - nothing happens after i am clicking "Login to PSN". Program just freezing and the only way to close it - go to task manager and shut down process. How to fix this login issue? I am using Windows 10 last version.
![screenshot_3](https://user-images.githubusercontent.com/41503312/50054082-e3a39d80-0146-11e9-932f-5f9b0016ac28.jpg)

**Comment by FrankyXD** [comment]
I got the exact same issue. Please help us :(

**Comment by Kiznel** [comment]
Same issue here:

From log.txt

`[18:29:59] - Error when logging in with tokens: PlayStationSharp.Exceptions.PlayStationApiException: Exception of type 'PlayStationSharp.Exceptions.PlayStationApiException' was thrown.
   at PlayStationSharp.Request.<>c__1`1.<SendPostRequest>b__1_0(Exception ex)
   at System.AggregateException.Handle(Func`2 predicate)
   at PlayStationSharp.Request.SendPostRequest[T](String url, Object data, String oAuthToken)
   at PlayStationSharp.Extensions.OAuthTokens.RefreshTokens()
   at PlayStationSharp.Extensions.OAuthTokens..ctor(String refreshToken)
   at PlayStationDiscord.TokenHandler.Check()
   at PlayStationDiscord.MainWindow.TryAutomaticLogin()
`

**Comment by Tustin** [comment]
I just released the newest version of PlayStationDiscord which has been completely rewritten and should fix any previous issues: 
https://github.com/Tustin/PlayStationDiscord/releases/tag/3.0.0

Just download `installer-PlayStationDiscord-3.0.0.exe` if you use Windows or `PlayStationDiscord-3.0.0.dmg` if you use Mac!
