### ISSUE TITLE
An error occurred while communicating with discord

### ISSUE THREAD

**Issue by tawer2000** [Tustin/PlayStationDiscord#171]
**Information**
- OS: Windows 10 x64
- Version: Latest

**Describe the bug**
An error occurred while communicating with discord

**Log**
[2021-05-05 11:17:18.529] [info] Saved new version of games.json
[2021-05-06 10:57:30.340] [info] PlayStationDiscord-Games has not been updated, using cached version
[2021-05-06 10:58:02.674] [info] Running refreshAuthTokensLoop
[2021-05-06 10:58:02.679] [info] Saved oauth tokens
[2021-05-06 10:58:03.118] [info] Starting rich presence loop
[2021-05-06 10:58:48.529] [info] Switching console to  PS5
[2021-05-06 10:58:48.548] [info] DiscordController init
[2021-05-06 10:58:48.549] [info] Switched console to PlayStation 5
[2021-05-06 10:58:48.549] [info] Status set to online
[2021-05-06 10:59:03.504] [info] Switching console to  PS5
[2021-05-06 10:59:03.505] [info] DiscordController init
[2021-05-06 10:59:03.505] [info] Switched console to PlayStation 5
[2021-05-06 10:59:03.506] [info] Status set to online
[2021-05-06 10:59:18.476] [info] Switching console to  PS5
[2021-05-06 10:59:18.477] [info] DiscordController init
[2021-05-06 10:59:18.477] [info] Switched console to PlayStation 5
[2021-05-06 10:59:18.477] [info] Status set to online
[2021-05-06 10:59:33.571] [info] Switching console to  PS5
[2021-05-06 10:59:33.572] [info] DiscordController init
[2021-05-06 10:59:33.572] [info] Switched console to PlayStation 5
[2021-05-06 10:59:33.573] [info] Status set to online
[2021-05-06 10:59:43.575] [error] An error occurred while communicating with Discord Error: RPC_CONNECTION_TIMEOUT
    at Timeout._onTimeout (C:\Program Files\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\client.js:107:47)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[2021-05-06 10:59:43.576] [warn] DiscordController disconnected
[2021-05-06 10:59:43.577] [info] Stopped rich presence loop

[log contents]
```

**Additional context**
Add any other context about the problem here.

**Comment by Quad-Plex** [comment]
I am havig the same issue

```
[2021-06-07 15:15:34.166] [info] DiscordController init
[2021-06-07 15:15:34.166] [info] Switched console to PlayStation Vita
[2021-06-07 15:15:34.166] [info] Status set to online
[2021-06-07 15:15:34.167] [info] Updated rich presence
[2021-06-07 15:15:44.180] [error] An error occurred while communicating with Discord Error: RPC_CONNECTION_TIMEOUT
    at Timeout.setTimeout (C:\Program Files\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\client.js:99:47)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at unrefdHandle (timers.js:509:7)
    at Timer.processTimers (timers.js:211:12)
[2021-06-07 15:15:46.306] [warn] DiscordController disconnected
[2021-06-07 15:15:46.307] [info] Stopped rich presence loop
```

**Comment by ratoro** [comment]
Also having a similar issue on 3.2.0

[2021-06-24 20:26:00.741] [info] Starting rich presence loop
[2021-06-24 20:26:00.897] [info] Switching console to  PS5
[2021-06-24 20:26:00.898] [info] DiscordController init
[2021-06-24 20:26:00.898] [info] Switched console to PlayStation 5
[2021-06-24 20:26:00.898] [info] Game has switched FINAL FANTASY VII REMAKE
[2021-06-24 20:26:00.899] [warn] Game icon not found in supported games store FINAL FANTASY VII REMAKE CUSA07211_00
[2021-06-24 20:26:00.899] [info] Updated rich presence
[2021-06-24 20:26:01.485] [info] Stopped rich presence loop
[2021-06-24 20:26:01.487] [error] An error occurred while communicating with Discord Error: connection closed
    at IPCTransport.<anonymous> (A:\Games\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\client.js:118:16)
    at Object.onceWrapper (events.js:417:26)
    at IPCTransport.emit (events.js:322:22)
    at A:\Games\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:141:18
    at decode (A:\Games\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.<anonymous> (A:\Games\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (events.js:310:20)
    at emitReadable_ (_stream_readable.js:543:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
[2021-06-24 20:26:01.487] [warn] DiscordController disconnected
[2021-06-24 20:26:01.488] [info] Stopped rich presence loop

**Comment by dystopia2017** [comment]
Same issue here, Version 3.2.0, Windows 10 with latest updates. After about 10 mins of working fine the error occurs
[main.log](https://github.com/Tustin/PlayStationDiscord/files/7577113/main.log)
