### ISSUE TITLE
When i open the app, all is shows is white

### ISSUE THREAD

**Issue by zRazy** [Tustin/PlayStationDiscord#52]
![discord](https://user-images.githubusercontent.com/51244181/58724941-c9e4d280-83d5-11e9-8beb-7059442cebde.png)

How can this be fixed?

**Comment by mostlyash** [comment]
Could you upload your **log.log** so that we can look into this. It's usually found in __Roaming/PlayStationDiscord/__ I believe.

**Comment by mateuszkozakiewicz** [comment]
Same thing happened to me today, additionally the program seems to log me out when I put the PC into sleep mode for the night, is there perhaps a time limit on how long the oauth token is valid for or is this something you can fix?

```
[2019-06-13 01:22:27.956] [info] Updated rich presence
[2019-06-13 01:22:42.952] [info] DiscordController stopped because the user is not online on PlayStation
[2019-06-13 08:42:14.548] [error] Failed fetching PSN profile Error: getaddrinfo ENOTFOUND us-prof.np.community.playstation.net us-prof.np.community.playstation.net:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[2019-06-13 08:42:14.571] [error] Failed refreshing PSN OAuth tokens Error: getaddrinfo ENOTFOUND auth.api.sonyentertainmentnetwork.com auth.api.sonyentertainmentnetwork.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
[2019-06-13 09:03:30.825] [info] PlayStationDiscord-Games has not been updated, using cached version
[2019-06-13 09:03:50.154] [info] Running refreshAuthTokensLoop
[2019-06-13 09:03:50.162] [info] Saved oauth tokens
[2019-06-13 09:03:50.668] [info] Starting rich presence loop
[2019-06-13 09:04:50.516] [error] Failed fetching PSN profile Error: getaddrinfo ENOTFOUND us-prof.np.community.playstation.net us-prof.np.community.playstation.net:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)

```
