### ISSUE TITLE
An error occurred while communicating with Discord

### ISSUE THREAD

**Issue by cleverkraft** [Tustin/PlayStationDiscord#94]
**Information**
- OS: macOS
- Version: 3.1.2

On launch of the app, the error displayed is "An error occurred while communicating with Discord. Please check the log file for additonal information." 

Log:

[2020-05-15 22:01:56.810] [info] Running refreshAuthTokensLoop
[2020-05-15 22:01:56.828] [info] Saved oauth tokens
[2020-05-15 22:01:57.241] [info] Starting rich presence loop
[2020-05-15 22:01:57.610] [info] Switching console to  PS4
[2020-05-15 22:01:57.611] [info] DiscordController init
[2020-05-15 22:01:57.611] [info] Switched console to PlayStation 4
[2020-05-15 22:01:57.612] [info] Game has switched Tom Clancy's The Division® 2
[2020-05-15 22:01:57.614] [warn] Game icon not found in supported games store Tom Clancy's The Division® 2 CUSA12639_00
[2020-05-15 22:01:57.614] [info] Updated rich presence
[2020-05-15 22:01:57.625] [error] An error occurred while communicating with Discord Error: Could not connect
    at Socket.onerror (/Applications/PlayStationDiscord.app/Contents/Resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2020-05-15 22:02:04.864] [warn] DiscordController disconnected
[2020-05-15 22:02:04.864] [info] Stopped rich presence loop

**Comment by cleverkraft** [comment]
This is running OS X 10.14.6

**Comment by norisio** [comment]
I'm on the same error. 

Even when PSD is running without error, the rich presence is not applied on Discord.

* PlayStationDiscord 3.1.2
* Windows 10 1909 (build 18363.836)
* Discord Stable 60315 (ad22003)

```
[error] An error occurred while communicating with Discord Error: connection closed
    at _expecting.forEach (C:\Program Files\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\client.js:107:20)
    at Map.forEach (<anonymous>)
    at IPCTransport.transport.once (C:\Program Files\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\client.js:106:25)
    at Object.onceWrapper (events.js:273:13)
    at IPCTransport.emit (events.js:182:13)
    at decode (C:\Program Files\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:137:18)
    at decode (C:\Program Files\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.socket.on (C:\Program Files\PlayStationDiscord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:534:12)
```

**Comment by Tustin** [comment]
Need to investigate this. Seems like an issue with the Discord RPC library I use.

**Comment by mattledger** [comment]
Same error as when Discord is not running?

**Comment by Overstuffedsofa** [comment]
Yes me too, dont think itll ever be fixed guys. Big Rip

**Comment by Tustin** [comment]
Try some of the suggestions posted here: https://github.com/iCrawl/discord-vscode/issues/85. This seems like an ongoing issue that I'm not sure I'll be able to fix since it's not an issue with this program.

**Comment by ghaztt** [comment]
im running discord and playstationdiscord with administrator , and don't worked

**Comment by xetsubou** [comment]
ps4 connects fine for me but ps3 gives me this error

![image](https://user-images.githubusercontent.com/68286491/87441197-d8358400-c5c0-11ea-99a7-0ea15e069c86.png)

**Comment by ghaztt** [comment]
psvita gives me this error

**Comment by Truefee** [comment]
Mine got resolved by signing out from both the apps. Then sign in again into discord and then playstation discord. Hope it helps.
